language: node_js
cache: yarn
env:
  global:
    - RUN_TESTS=`echo True`
after_script:
- echo $RUN_TESTS
sudo: false
jobs:
  include:
    - stage: test0
      script: `echo "*************Test0 suite**********************"`

    - stage: test1
      if: env(RUN_TESTS) =~ /^True$/
      script: `echo "*************Test1 suite**********************"`

    - stage: test2
      if: env(RUN_TESTS) =~ /^True$/
      script: `echo "*************Test2 suite**********************"`

# ----- Skip this until docs deploy works again ------
#- provider: script
#  skip_cleanup: true
#  script: scripts/docs-deploy.sh
#  on:
#    tags: true
#before_install:
#- openssl aes-256-cbc -K $encrypted_310f735a6883_key -iv $encrypted_310f735a6883_iv -in deploy_rsa.enc -out deploy_rsa -d
#after_install:
#- ssh-agent -k