language: node_js
cache: yarn
env:
  global:
    - RUN_TESTS=`echo True`
after_script:
- echo $RUN_TESTS
sudo: false
jobs:
  include:
    - stage: CONTROL
      script: echo "*************Test0 suite**********************"
    - stage: EXACT
      if: env(RUN_TESTS) = True
      script: echo "*************Test1 suite**********************"
    - stage: EXACT_REGEX
      if: env(RUN_TESTS) =~ /^True$/
      script: echo "*************Test2 suite**********************"
    - stage: SUBSTRING_REGEX_NEWLINE
      if: env(RUN_TESTS) =~ /^True\n$/
      script: echo "*************Test3 suite**********************"
    - stage: SUBSTRING_REGEX
      if: env(RUN_TESTS) =~ /.*True.*/
      script: echo "*************Test4 suite**********************"
    - stage: EXACT_QUOTED_STRING
      if: env(RUN_TESTS) = "True"
      script: echo "*************Test5 suite**********************"
    - stage: LITERAL
      if: env(RUN_TESTS) = "echo True"
      script: echo "*************Test6 suite**********************"
    - stage: TICK_LITERAL
      if: env(RUN_TESTS) = "`echo True`"
      script: echo "*************Test7 suite**********************"

# ----- Skip this until docs deploy works again ------
#- provider: script
#  skip_cleanup: true
#  script: scripts/docs-deploy.sh
#  on:
#    tags: true
#before_install:
#- openssl aes-256-cbc -K $encrypted_310f735a6883_key -iv $encrypted_310f735a6883_iv -in deploy_rsa.enc -out deploy_rsa -d
#after_install:
#- ssh-agent -k