on: 
  pull_request:
  issue_comment:
    types: [edited]

jobs:
  update_changelog_job:
    runs-on: ubuntu-latest
    name: Update CHANGELOG.md
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Update changelog
        uses: ./.github_actions/ # Uses an action in the root directory
        id: update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changelog
        if: steps.update.outputs.success == 'true'
        run: |
          git config --global user.name 'Changelog Bot'
          git config --global user.email 'changelog-bot@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -am "Updated CHANGELOG.MD"
          git push
            